
#include "ProfileAdvisor.h"
#include "Logger.h"
#include <sstream>
#include <fstream>
#include <algorithm>
#include <cctype>

namespace OSA {

namespace {

std::wstring lower(std::wstring s) {
    std::transform(s.begin(), s.end(), s.begin(),
                   [](wchar_t c){ return (wchar_t)towlower(c); });
    return s;
}

int pxFromRes(const std::wstring& res) {
    int p = 1920;
    auto x = res.find(L'x');
    if (x != std::wstring::npos) {
        p = std::stoi(res.substr(0, x));
    }
    return p;
}

const wchar_t* upscalerName(const std::wstring& u) {
    if (u == L"dlss")  return L"DLSS";
    if (u == L"fsr3")  return L"FSR 3.1";
    if (u == L"xess")  return L"XeSS";
    return L"Auto";
}

} 

ProfileDecision ProfileAdvisor::advise(const InstallOptions& opt) {
    ProfileDecision d;

    static const std::pair<const wchar_t*, const wchar_t*> kInjections[] = {
        {L"winmm",    L"winmm.dll"},
        {L"version",  L"version.dll"},
        {L"dxgi",     L"dxgi.dll"},
        {L"d3d12",    L"d3d12.dll"},
        {L"dbghelp",  L"dbghelp.dll"},
        {L"wininet",  L"wininet.dll"},
        {L"winhttp",  L"winhttp.dll"},
    };
    d.injectDllName = L"winmm.dll";
    for (auto& kv : kInjections) {
        if (opt.injection == kv.first) { d.injectDllName = kv.second; break; }
    }
    d.reasons.push_back(L"注入 DLL: " + d.injectDllName);

    std::wstring up = opt.upscaler;
    std::wstring gpuTier(opt.gpu.tier.begin(), opt.gpu.tier.end());
    if (up == L"auto" || up.empty()) {
        if (opt.gpu.vendor == L"NVIDIA") up = L"dlss";
        else if (opt.gpu.vendor == L"Intel" && gpuTier != L"low") up = L"xess";
        else up = L"fsr3";
    }
    
    if (opt.game.acLevel == L"extreme") {
        up = L"fsr3";
        d.reasons.push_back(L"检测到极严反作弊，强制 FSR 3.1");
    }
    d.upscalerFinal = up;
    d.reasons.push_back(L"超采样方案: " + std::wstring(upscalerName(up)));

    int px = pxFromRes(opt.resolution);
    if (gpuTier == L"low") d.qualityPreset = L"ultra_perf";
    else if (px <= 1920) d.qualityPreset = (gpuTier == L"ultra") ? L"quality" : L"performance";
    else if (px <= 2560) d.qualityPreset = (gpuTier == L"ultra" || gpuTier == L"high") ? L"quality" : L"balanced";
    else if (px <= 3440) d.qualityPreset = (gpuTier == L"low") ? L"performance" : L"balanced";
    else d.qualityPreset = (gpuTier == L"ultra") ? L"quality" : (gpuTier == L"low") ? L"balanced" : L"balanced";
    d.reasons.push_back(L"质量预设: " + d.qualityPreset);

    d.enableFG = opt.fg;
    if (opt.game.acLevel == L"extreme") d.enableFG = false;
    if (gpuTier == L"low") d.enableFG = false;
    d.reasons.push_back(d.enableFG ? L"帧生成: 开启" : L"帧生成: 关闭");

    d.sharpness = opt.sharpen ? 0.5f : 0.0f;

    if (d.upscalerFinal == L"dlss") {
        d.dlssPreset = (gpuTier == L"ultra" || gpuTier == L"high") ? L"K" : L"F";
    } else {
        d.dlssPreset = L"";
    }

    {
        std::ostringstream os;
        os << "; Auto-generated by OptiScaler Assistant (changed keys only)\n";
        auto w2s = [](const std::wstring& w) {
            if (w.empty()) return std::string("");
            int n = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), nullptr, 0, nullptr, nullptr);
            std::string s; s.resize(n);
            WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), s.data(), n, nullptr, nullptr);
            return s;
        };
        os << "; GPU: "  << w2s(opt.gpu.name) << " (" << w2s(opt.gpu.vendor) << ")\n";
        os << "; Game: " << w2s(opt.game.exeName)
           << " [" << w2s(opt.game.gameType) << "]\n";
        os << "\n[Upscalers]\n";
        os << "Upscaler=" << (up == L"dlss" ? "dlss" : up == L"xess" ? "xess" : "fsr31") << "\n";
        os << "QualityOverride=" << (d.qualityPreset == L"ultra_perf" ? 0
                                    : d.qualityPreset == L"performance" ? 1
                                    : d.qualityPreset == L"balanced" ? 2
                                    : d.qualityPreset == L"quality" ? 3 : 0) << "\n";
        if (up == L"dlss") {
            os << "\n[DLSS]\n";
            if (!d.dlssPreset.empty()) os << "Preset=" << w2s(d.dlssPreset) << "\n";
            os << "RenderPresetOverride=true\n";
        }
        os << "\n[Sharpness]\n";
        os << "Enabled=" << (opt.sharpen ? "true" : "false") << "\n";
        os << "Sharpness=" << d.sharpness << "\n";
        os << "\n[FrameGen]\n";
        os << "Enabled=" << (d.enableFG ? "true" : "false") << "\n";
        if (d.enableFG) {
            os << "fgType=fsr31\n";
        }
        os << "\n[Input]\n";
        os << "ShortcutKey=" << w2s(opt.hotkeyMenu) << "\n";
        d.iniContent = os.str();
    }

    return d;
}

std::wstring ProfileAdvisor::toJson(const ProfileDecision& d) {
    std::wstring json = L"{";
    json += L"\"injectDllName\":\"" + d.injectDllName + L"\",";
    json += L"\"upscalerFinal\":\"" + d.upscalerFinal + L"\",";
    json += L"\"qualityPreset\":\"" + d.qualityPreset + L"\",";
    json += L"\"enableFG\":"     + std::wstring(d.enableFG ? L"true" : L"false") + L",";
    json += L"\"sharpness\":"    + std::to_wstring(d.sharpness) + L",";
    json += L"\"dlssPreset\":\"" + d.dlssPreset + L"\"";
    json += L"}";
    return json;
}

} 
